import 'dart:convert';

// List<Autogenerated> upload3FromJson(String str) => List<Autogenerated>.from(
//     json.decode(str).map((x) => Autogenerated.fromJson(x)));

// String upload3ToJson(List<Autogenerated> data) =>
//     json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class Autogenerated {
  Autogenerated({required this.status, required this.chk, required this.token});

  int? status;
  String? chk;
  String? token;

  factory Autogenerated.fromJson(Map<String, dynamic> json) => Autogenerated(
        status: json["status"],
        chk: json["chk"],
        token: json["token"],
      );

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['chk'] = this.chk;
    data['token'] = this.token;
    return data;
  }
}
